version: '3'

services:

  app:
    build: .
    environment:
      APP_DIR:         "${APP_DIR}"
      APP_HZ_HOST:     "${APP_HZ_HOST}"
      APP_HZ_PORT:     "${APP_HZ_PORT}"
      APP_HZ_DATABASE: "${APP_HZ_DATABASE}"
      APP_HZ_USER:     "${APP_HZ_USER}"
      APP_HZ_PASSWORD: "${APP_HZ_PASSWORD}"

    dns:
     - "$DNS_1"
     - "$DNS_2"
    working_dir: "${APP_DIR}" 
    volumes:
     - "${PWD}:${APP_DIR}"

